apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: jubri7/auth2
        env:
          - name: MONGODB
            value: "mongodb://auth-mongo-service:27017/auth"
          - name: SESSION
            valueFrom:
              secretKeyRef:
                name: session-secret
                key: SESSION
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: google
                key: GOOGLE_CLIENT_ID
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google
                key: GOOGLE_CLIENT_SECRET
          - name: REDIS
            value: auth-redis-service
---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
  - port: 3000
    targetPort: 3000
